const CitiesModel = require("../models/citiesModel");
const placesToVisitSchema = require("../models/placesToVisitModel");
const UsersModel = require("../models/usersModel");
const citiesModel = require("../models/citiesModel");


async function createCity(req, res, next) {
    try {
        if (!req.body.isAdmin) {
            return res.status(403).json({ message: "Access denied. Only admins can create cities." });
        }

        if (typeof req.body.cityName !== 'string' || req.body.cityName.trim() === "") {
            return res.status(400).json({ message: "Invalid cityName: must be a non-empty string" });
        }
        if (typeof req.body.country !== 'string' || req.body.country.trim() === "") {
            return res.status(400).json({ message: "Invalid country: must be a non-empty string" });
        }
        if (typeof req.body.statistics !== 'string' || req.body.statistics.trim() === "") {
            return res.status(400).json({ message: "Invalid statistics: must be a non-empty string" });
        }
        if (typeof req.body.facts !== 'string' || req.body.facts.trim() === "") {
            return res.status(400).json({ message: "Invalid facts: must be a non-empty string" });
        }
        if (!Array.isArray(req.body.tags) || req.body.tags.length === 0) {
            return res.status(400).json({ message: "Tags must be a non-empty array" });
        }

        const city = new CitiesModel(req.body);
        await city.save();
        res.status(201).json(city);
    } catch (err) {
        if (err.name === 'ValidationError' && err.errors && err.errors.tags) {
            return res.status(400).json({ message: "Invalid tag(s) provided. Please provide valid tags." });
        }
        next(err);
    }
}

async function createPlaceInCity(req, res) {
    const cityId = req.params.id;
    try {
        if (!req.body.isAdmin) {
            return res.status(403).json({ message: "Access denied. Only admins can create cities." });
        }

        const city = await CitiesModel.findById(cityId);
        if (!city) {
            return res.status(404).json({ error: "City not found" });
        }
        if (typeof req.body.placeName !== 'string' || req.body.placeName.trim() === '') {
            return res.status(400).json({ message: "Invalid placeName: must be a non-empty string" });
        }
        if (typeof req.body.address !== 'string' || req.body.address.trim() === '') {
            return res.status(400).json({ message: "Invalid address: must be a non-empty string" });
        }
        if (typeof req.body.rating !== 'number' || req.body.rating < 0.0 || req.body.rating > 5.0) {
            return res.status(400).json({ message: "Invalid rating: must be a number between 0.0 and 5.0" });
        }
        if (typeof req.body.content !== 'string' || req.body.content.trim() === '') {
            return res.status(400).json({ message: "Invalid content: must be a non-empty string" });
        }
        if (!Array.isArray(req.body.tags) || req.body.tags.length === 0) {
            return res.status(400).json({ message: "Tags cannot be an empty array" });
        }

        const placeToVisit = new placesToVisitSchema({
            placeName: req.body.placeName,
            address: req.body.address,
            rating: req.body.rating,
            content: req.body.content,
            tags: req.body.tags,
            city: city._id,
        });

        await placeToVisit.save();
        city.placesToVisit.push(placeToVisit._id);
        await city.save();
        res.status(201).json(placeToVisit);
    } catch (err) {
        if (err.name === 'ValidationError' && err.errors && err.errors.tags) {
            return res.status(400).json({ message: "Invalid tag(s) provided. Please provide valid tags." });
        }
        console.error("Error creating the place to visit:", err);
        res.status(500).json({ message: "An error occurred while creating the place", error: err.message });
    }
}


async function getOneCity(req, res) { 
    const cityId = req.params.id;

    // check if the cityId is in the valid format (generated by mongoose)
    if (!cityId || !cityId.match(/^[0-9a-fA-F]{24}$/)) {
        return res.status(400).json({ message: 'Invalid city ID format.' });
    }

    try {
        const city = await CitiesModel.findById(cityId);
        if (!city) {
            return res.status(404).json({ message: "City not found" });
        }
        res.status(200).json(city); 
    } catch (err) {
        res.status(500).json({ error: 'An error occurred while fetching the city.' }); 
    }
}

async function getAllCities(req, res) {
    try {
        const { tags, minRating, maxRating, sortByRating } = req.query;

        let filter = {};

        if (tags) {
            const tagsArray = tags.split(','); // Convert tags string to array (comma-separated)
            filter.tags = { $all: tagsArray };
        }

        if (minRating || maxRating) {
            filter.rating = {};
            if (minRating) filter.rating.$gte = parseFloat(minRating);
            if (maxRating) filter.rating.$lte = parseFloat(maxRating);
        }

        let sortOption = {};

        if (sortByRating) {
            sortOption.rating = sortByRating === 'asc' ? 1 : -1;
        }

        const cities = await CitiesModel.find(filter).sort(sortOption);

        if (!cities || cities.length === 0) {
            return res.status(404).json({ message: 'No cities found.' });
        }
        res.status(200).json({ cities });
    } catch (error) {
        res.status(500).json({ error: 'An error occurred while fetching cities.' });
    }
}

async function getOnePlaceFromCity(req, res){
    const cityId = req.params.cityId;
    const address = req.params.address;
    
    try{
        const city = await CitiesModel.findOne(cityId).populate('placesToVisit');
        if (!city){
            return res.status(404).json({ message: "City not found" });
        }
        if (!city.placesToVisit || city.placesToVisit.length === 0) {
            return res.status(404).json({ message: "No places are found in this city" });
        }

        const place = city.placesToVisit.find(place => place.address === address);
        if (!place) {
            return res.status(404).json({ message: "Place not found" });
        }
        res.status(200).json(place);
    } catch (err) {
        res.status(500).json({ error: 'An error occurred while fetching the places.' });
    }
}

async function getPlacesFromCity(req, res){
    const cityId = req.params.cityId;
    try{
        const city = await CitiesModel.findOne(cityId).populate('placesToVisit');
        if (!city){
            return res.status(404).json({ message: "City not found" });
        }
        if (!city.placesToVisit || city.placesToVisit.length === 0){
            return res.status(404).json({ message: "No places are found" });
        }
        res.status(200).json(city.placesToVisit);
    } catch (err) {
        console.error(err);
        res.status(500).json({ error: 'An error occurred while fetching the places.' });
    }
}

async function updateCity(req, res, next) {
    const cityId = req.params.id;

    try {
        if (!req.body.isAdmin) {
            return res.status(403).json({ message: "Access denied. Only admins can update cities." });
        }

        const city = await CitiesModel.findById(cityId);
        if (!city) {
            return res.status(404).json({ message: "City not found" });
        }
        if (req.body.cityName !== undefined) {
            if (typeof req.body.cityName !== 'string' || req.body.cityName.trim() === "") {
                return res.status(400).json({ message: "Invalid cityName: must be a non-empty string" });
            }
            city.cityName = req.body.cityName;
        }
        if (req.body.country !== undefined) {
            if (typeof req.body.country !== 'string' || req.body.country.trim() === "") {
                return res.status(400).json({ message: "Invalid country: must be a non-empty string" });
            }
            city.country = req.body.country;
        }
        if (req.body.statistics !== undefined) {
            if (typeof req.body.statistics !== 'string' || req.body.statistics.trim() === "") {
                return res.status(400).json({ message: "Invalid statistics: must be a non-empty string" });
            }
            city.statistics = req.body.statistics;
        }
        if (req.body.facts !== undefined) {
            if (typeof req.body.facts !== 'string' || req.body.facts.trim() === "") {
                return res.status(400).json({ message: "Invalid facts: must be a non-empty string" });
            }
            city.facts = req.body.facts;
        }
        if (Array.isArray(req.body.tags)) {
            if (req.body.tags.length === 0) {
                return res.status(400).json({ message: "Tags cannot be an empty array" });
            }
            city.tags = req.body.tags;
        }
        await city.save();
        res.status(200).json(city);
    } catch (err) {
        if (err.name === 'ValidationError' && err.errors && err.errors.tags) {
            return res.status(400).json({ message: "Invalid tag(s) provided. Please provide valid tags." });
        }
        next(err);
    }
}


async function patchCity(req, res, next){
    const cityId = req.params.id;

    try{
        if (!req.body.isAdmin) {
            return res.status(403).json({ message: "Access denied. Only admins can patch places." });
        }
        const city = await CitiesModel.findById(cityId);
        if (city == null){
            return res.status(404).json({"message": "City not found"});
        }
        city.statistics = req.body.statistics || city.statistics;
        city.facts = req.body.facts || city.facts;
        city.tags = req.body.tags || city.tags;
        await city.save();
        res.status(200).json(city);
    } catch (err) {
        if (err.name === 'ValidationError' && err.errors && err.errors.tags) {
            return res.status(400).json({ message: "Invalid tag(s) provided. Please provide valid tags." });
        }
        next(err);
    }
};


async function deleteOneCity(req, res) {
    const cityId = req.params.id;
    try {
        const city = await CitiesModel.findByIdAndDelete(cityId);
        if (!city) {
            return res.status(404).json({ "message": "City not found" });
        }
        res.status(200).json({ "message": "City deleted successfully", city });
    } catch (err) {
        console.error(err);
        res.status(500).json({ "message": "Internal server error" });
    }
}


module.exports = {
    createCity,
    createPlaceInCity,
    getAllCities,
    getOneCity,
    getPlacesFromCity,
    getOnePlaceFromCity,
    patchCity,
    updateCity,
    deleteOneCity
}